# CSV파일 입출력
## 파일 입력
### read_csv()
CSV 파일로부터 데이터를 읽어 데이터프레임을 만들 때 사용한다.

In [4]:
import pandas as pd
import numpy as np

In [5]:
sample1 = pd.read_csv("sample1.csv")
sample1

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [6]:
sample2 = pd.read_csv("sample2.csv" , names = ["c1", "c2", "c3"])
sample2

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [8]:
sample1 = pd.read_csv("sample1.csv", index_col="c1")
sample1

      c2      c3
c1
1   1.11     one
2   2.22     two
3   3.33   three

In [10]:
sample3 = pd.read_csv("sample3.txt", sep='\t')
sample3

         C1        C2        C3       C4
0  0.179181 -1.538472  1.347553  0.43381
1  1.024209  0.087307 -1.281997  0.49265
2  0.417899 -2.002308  0.255245 -1.10515

In [11]:
sample4 = pd.read_csv("sample4.txt", skiprows=[0,1])
sample4

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [13]:
sample5 = pd.read_csv("sample5.csv", na_values=["누락"])
sample5

    c1    c2      c3
0  1.0  1.11     one
1  2.0   NaN     two
2  NaN  3.33   three

-------------------
## to_csv()
### 데이터프레임 값을 CSV 파일로 출력하고 싶을 때 사용한다.

In [18]:
df = sample5 = pd.read_csv("sample5.csv", na_values=["누락"])
df.to_csv('sample6.csv')

In [19]:
df.to_csv('sample7.csv', sep="|")

In [26]:
df.to_csv('sample8.csv', na_rep="없음")

In [24]:
df.to_csv('sample9.csv', index=False, header=True)

In [25]:
df.index = ["a", "b", "c"]
df.to_csv('sample10.csv', index=True, header=False)

-------------
## 통계함수

In [27]:
[N, T, F] = [np.nan, True, False]

idx = [['IDX1', 'IDX1', 'IDX2', 'IDX2'], ['row1', 'row2', 'row3', 'row4']]
col = [['COL1', 'COL1', 'COL2', 'COL2'], ['val1', 'val2', 'val3', 'val4']]
data = [[N, 13, 3, 4], [5, 7, 10, 8], [15, 6, N, 3], [2, 14, 9, 1]]

df = pd.DataFrame(data, idx, col)
df

           COL1       COL2
           val1 val2  val3 val4
IDX1 row1   NaN   13   3.0    4
     row2   5.0    7  10.0    8
IDX2 row3  15.0    6   NaN    3
     row4   2.0   14   9.0    1

In [29]:
df.max()

COL1  val1    15.0
      val2    14.0
COL2  val3    10.0
      val4     8.0
dtype: float64

In [30]:
df.max(axis=1)

IDX1  row1    13.0
      row2    10.0
IDX2  row3    15.0
      row4    14.0
dtype: float64

In [31]:
df.max(axis=0)

COL1  val1    15.0
      val2    14.0
COL2  val3    10.0
      val4     8.0
dtype: float64

In [32]:
df.max(skipna=True)

COL1  val1    15.0
      val2    14.0
COL2  val3    10.0
      val4     8.0
dtype: float64

In [33]:
df.max(skipna=False)

COL1  val1     NaN
      val2    14.0
COL2  val3     NaN
      val4     8.0
dtype: float64

In [34]:
df.min(skipna=False)

COL1  val1    NaN
      val2    6.0
COL2  val3    NaN
      val4    1.0
dtype: float64

In [35]:
df.min(skipna=True)

COL1  val1    2.0
      val2    6.0
COL2  val3    3.0
      val4    1.0
dtype: float64

In [36]:
df.min()

COL1  val1    2.0
      val2    6.0
COL2  val3    3.0
      val4    1.0
dtype: float64

In [38]:
df.mean()

COL1  val1     7.333333
      val2    10.000000
COL2  val3     7.333333
      val4     4.000000
dtype: float64

In [40]:
df.mean(axis=0)

COL1  val1     7.333333
      val2    10.000000
COL2  val3     7.333333
      val4     4.000000
dtype: float64

In [41]:
df.mean(axis=1)

IDX1  row1    6.666667
      row2    7.500000
IDX2  row3    8.000000
      row4    6.500000
dtype: float64

In [42]:
df.median()

COL1  val1     5.0
      val2    10.0
COL2  val3     9.0
      val4     3.5
dtype: float64

In [43]:
df.median(axis=0)

COL1  val1     5.0
      val2    10.0
COL2  val3     9.0
      val4     3.5
dtype: float64

In [44]:
df.median(axis=1)

IDX1  row1    4.0
      row2    7.5
IDX2  row3    6.0
      row4    5.5
dtype: float64

In [49]:
df.mod(2) # 나머지 연산

          COL1      COL2
          val1 val2 val3 val4
IDX1 row1  NaN    1  1.0    0
     row2  1.0    1  0.0    0
IDX2 row3  1.0    0  NaN    1
     row4  0.0    0  1.0    1

In [50]:
df.std(axis=0)  #표준편차

COL1  val1    6.806859
      val2    4.082483
COL2  val3    3.785939
      val4    2.943920
dtype: float64

In [47]:
df.var(axis=0)  # 분산

COL1  val1    46.333333
      val2    16.666667
COL2  val3    14.333333
      val4     8.666667
dtype: float64

In [51]:
col1 = [1,2,3,4,5,6]
col2 = [1,4,2,8,16,32]
col3 = [6,5,4,3,2,1]
data = {"col1":col1,"col2":col2,"col3":col3}
df = pd.DataFrame(data)
df

   col1  col2  col3
0     1     1     6
1     2     4     5
2     3     2     4
3     4     8     3
4     5    16     2
5     6    32     1

In [53]:
df.corr(method='pearson', numeric_only=True)   # 상관계수 분석

          col1      col2      col3
col1  1.000000  0.887739 -1.000000
col2  0.887739  1.000000 -0.887739
col3 -1.000000 -0.887739  1.000000

In [54]:
df = pd.read_csv("./titanic/train.csv")
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [55]:
df.sort_index(ascending=False)  # 내림차순을 의미함 왜냐하면 False라서

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [58]:
data = {
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 2632035],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
}
columns = ["도시", "연도", "인구", "지역"]

df1 = pd.DataFrame(data, columns=columns)
df1

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010  2632035  수도권

In [62]:
df1.pivot(index="도시", columns="연도", values="인구")

연도       2005       2010       2015
도시
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN  2632035.0  2890451.0

In [64]:
#df1.pivot(index="지역", columns="연도", values="인구")  
## 문제점이 있다.
#  Index contains duplicate entries, cannot reshape 오류가 난다
# index와 columns 조합이 하나의 값만 가져야 하는데, 지금 데이터는 그렇지 않기 때문입니다.

### pivot_table
형식) pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, margins_name='All')
- data: 분석할 데이터프레임 (메서드일 때는 필요하지 않음)
- values: 분석할 데이터프레임에서 분석할 열
- index: 행 인덱스로 들어갈 키 열 또는 키 열의 리스트
- columns: 열 인덱스로 들어갈 키 열 또는 키 열의 리스트
- aggfunc: 분석 메서드 지정
- fill_value: NaN 대체 값 설정
- margins: 오른쪽과 아래에 합계를 붙일지 여부 지정
- margins_name: 합계 열(행)의 이름 지정

In [65]:
df2 = pd.DataFrame({
    'key1': ['A', 'A', 'B', 'B', 'A'],
    'key2': ['one', 'two', 'one', 'two', 'one'],
    'data1': [1, 2, 3, 4, 5],
    'data2': [10, 20, 30, 40, 50]
})

df2

  key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [67]:
df2.pivot_table("data1", "key1", "key2") #  aggfunc='mean'이게 지금 없음 없으면 자동처리 / 만약 값이 여러개면 평균을 구해서 표현해줌
# 변경도 가능함

key2  one  two
key1
A     3.0  2.0
B     3.0  4.0

In [68]:
df2.pivot_table("data1", "key1", "key2", aggfunc=  sum)

key2  one  two
key1
A       6    2
B       3    4

In [69]:
df2.pivot_table("data1", "key1", "key2", margins=True)

key2  one  two       All
key1
A     3.0  2.0  2.666667
B     3.0  4.0  3.500000
All   3.0  3.0  3.000000

In [70]:
df2.pivot_table("data1", "key1", "key2", margins=True, margins_name="평균")

key2  one  two        평균
key1
A     3.0  2.0  2.666667
B     3.0  4.0  3.500000
평균    3.0  3.0  3.000000

In [71]:
df2.pivot_table("data1", index = ["key1", "key2"] )

           data1
key1 key2
A    one     3.0
     two     2.0
B    one     3.0
     two     4.0