In [38]:
pd.set_option('display.max_seq_items', None) # 텍스트 길이 다 보기

# 데이퍼 프레임
## 타이타닉 예제 실습
--------------------------------

첫번쨰 작업

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./titanic/train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
"""
PassengerId: 승객 ID

Survived: 생존 여부 (0 = 사망, 1 = 생존)

Pclass: 객실 등급 (1 = 1등석, 2 = 2등석, 3 = 3등석)

Name: 이름

Sex: 성별

Age: 나이

SibSp: 함께 탑승한 형제자매/배우자 수

Parch: 함께 탑승한 부모/자녀 수

Ticket: 티켓 번호

Fare: 탑 요금

Cabin: 객실 번호 또는 수화물 번호

Embarked: 탑승 항구 (C = Cherbourg, Q = Queenstown, S = Southampton)
"""

'\nPassengerId: 승객 ID\n\nSurvived: 생존 여부 (0 = 사망, 1 = 생존)\n\nPclass: 객실 등급 (1 = 1등석, 2 = 2등석, 3 = 3등석)\n\nName: 이름\n\nSex: 성별\n\nAge: 나이\n\nSibSp: 함께 탑승한 형제자매/배우자 수\n\nParch: 함께 탑승한 부모/자녀 수\n\nTicket: 티켓 번호\n\nFare: 탑 요금\n\nCabin: 객실 번호 또는 수화물 번호\n\nEmbarked: 탑승 항구 (C = Cherbourg, Q = Queenstown, S = Southampton)\n'

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [5]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [6]:
df.describe() # 기초 통계를 보여

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [8]:
# df.corr()
df.select_dtypes(include='number').corr()
df.corr(numeric_only=True) # 동일한 내용

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [9]:
df['SibSp'].corr(df["Parch"])

np.float64(0.41483769862015646)

In [10]:
df[["SibSp", "Parch", "Fare"]].corr() # []로 묶어서 함

          SibSp     Parch      Fare
SibSp  1.000000  0.414838  0.159651
Parch  0.414838  1.000000  0.216225
Fare   0.159651  0.216225  1.000000

In [11]:
df.mean(numeric_only=True)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [12]:
df.std(numeric_only=True)

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [13]:
df.groupby("Survived").mean(numeric_only=True)

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [14]:
df.groupby(["Sex","Survived"]).mean(numeric_only=True)

                 PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived
female 0          434.851852  2.851852  25.046875  1.209877  1.037037
       1          429.699571  1.918455  28.847716  0.515021  0.515021
male   0          449.121795  2.476496  31.618056  0.440171  0.207265
       1          475.724771  2.018349  27.276022  0.385321  0.357798

                      Fare
Sex    Survived
female 0         23.024385
       1         51.938573
male   0         21.960993
       1         40.821484

In [15]:
df1 = df.rename({"Name":"이름"}, axis=1)
df1.head(2)

,PassengerId,Survived,Pclass,이름,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [16]:
df1 = df.rename(columns={"Name":"이름"})
df1.head(2)

,PassengerId,Survived,Pclass,이름,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [17]:
df3 = df.Sex.map(lambda x : 0 if x == "female" else 1)
df3.head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [18]:
def n_square(x):
    return x ** 2

In [19]:
df4_1 = df["Age"].map(n_square)
df4_1

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
        ...
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [20]:
def n_square(x, n):
    return x ** n

In [21]:
df4 = df[["Age", "SibSp", "Fare"]].apply(n_square, n=2)
df4

        Age  SibSp         Fare
0     484.0      1    52.562500
1    1444.0      1  5081.308859
2     676.0      0    62.805625
3    1225.0      1  2819.610000
4    1225.0      0    64.802500
..      ...    ...          ...
886   729.0      0   169.000000
887   361.0      0   900.000000
888     NaN      1   549.902500
889   676.0      0   900.000000
890  1024.0      0    60.062500

[891 rows x 3 columns]

-------------------
## 객체 연산

In [22]:
data = [[1, 10, 100], [2, 20, 200], [3, 30, 300]]
col = ["col1", 'col2', 'col3']
row = ['row1', "row2", "row3"]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3
row1     1    10   100
row2     2    20   200
row3     3    30   300

In [23]:
reslut = df.add(1) # sub 빼기 / mul() / div()
reslut

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [24]:
reslut = df + 1
reslut

      col1  col2  col3
row1     2    11   101
row2     3    21   201
row3     4    31   301

In [25]:
data2 = [[3], [4], [5]]
df2 = pd.DataFrame(data2, index=["row1", "row2", "row3"], columns=["col"])
df2

      col
row1    3
row2    4
row3    5

In [26]:
re = df.add(df2)
re

      col  col1  col2  col3
row1  NaN   NaN   NaN   NaN
row2  NaN   NaN   NaN   NaN
row3  NaN   NaN   NaN   NaN

In [27]:
re = df.add(df2, fill_value=0)
re

      col  col1  col2   col3
row1  3.0   1.0  10.0  100.0
row2  4.0   2.0  20.0  200.0
row3  5.0   3.0  30.0  300.0

In [28]:
col = ["col1" , "col2"]
row = ["row1", "row2"]
data1 = [[1,2],[3,4]]
data2 = [[5,6],[7,8]]
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [29]:
df1

   0  1
0  1  2
1  3  4

In [30]:
df2

   0  1
0  5  6
1  7  8

In [31]:
df3 = df1.dot(df2)

In [32]:
df3

    0   1
0  19  22
1  43  50

In [33]:
import numpy as np

col = ["col1", "col2", "col3"]
row = ["row1", "row2", "row3"]
data = np.random.rand(3,3)*100
df = pd.DataFrame(data, row, col)
df

           col1       col2       col3
row1   9.056172   6.490765  14.221626
row2  80.706143  68.283578  91.689090
row3  59.974236  41.701704  89.002516

In [34]:
df.round(2)
df.round(0)

      col1  col2  col3
row1   9.0   6.0  14.0
row2  81.0  68.0  92.0
row3  60.0  42.0  89.0

In [35]:
import numpy as np

col = ["col1", "col2", "col3"]
row = ["row1", "row2", "row3"]
data = [[1,2,3], [4,5,6],[7,np.nan,9]]
df = pd.DataFrame(data, row, col)
df

      col1  col2  col3
row1     1   2.0     3
row2     4   5.0     6
row3     7   NaN     9

In [36]:
df.sum(axis=0) # 각 열(column)의 합
df.sum(axis=1) #

row1     6.0
row2    15.0
row3    16.0
dtype: float64

In [37]:
df.sum(axis=0, skipna=False)

col1    12.0
col2     NaN
col3    18.0
dtype: float64

In [38]:
df.prod(axis=0)

col1     28.0
col2     10.0
col3    162.0
dtype: float64

In [39]:
df.prod(axis=1)

row1      6.0
row2    120.0
row3     63.0
dtype: float64

In [40]:
df.prod(axis=0, skipna=False)

col1     28.0
col2      NaN
col3    162.0
dtype: float64

In [41]:
df.transpose()

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [42]:
df.T

      row1  row2  row3
col1   1.0   4.0   7.0
col2   2.0   5.0   NaN
col3   3.0   6.0   9.0

In [43]:
idx = ["A","A","B","B","B","C","C","C","D","D","D","D","E","E","E"]
col = ["col1", "col2", "col3"]
data = np.random.randint(0,9,(15,3))  # 15행 3열
df = pd.DataFrame(data, idx, col).reset_index() # 인댁스를 기존에 있던 인덱스를 지우고 새롭게 만드는 것을 말한다

df

   index  col1  col2  col3
0      A     0     7     8
1      A     6     8     6
2      B     6     5     5
3      B     2     1     6
4      B     0     5     2
5      C     7     7     3
6      C     5     6     0
7      C     6     6     0
8      D     0     1     8
9      D     7     3     3
10     D     6     1     4
11     D     4     8     5
12     E     1     2     2
13     E     2     2     0
14     E     4     1     2

In [44]:
df.groupby("index").mean()  # 데이터 중 같은 인덱스를 가진 친구들을 더해서 mean

           col1      col2      col3
index
A      3.000000  7.500000  7.000000
B      2.666667  3.666667  4.333333
C      6.000000  6.333333  1.000000
D      4.250000  3.250000  5.000000
E      2.333333  1.666667  1.333333

In [45]:
df.groupby("index").count()  # 인덱스를 기준으로 한다.

       col1  col2  col3
index
A         2     2     2
B         3     3     3
C         3     3     3
D         4     4     4
E         3     3     3

In [46]:
df.groupby("index").agg(["mean", "sum"])

           col1          col2          col3
           mean sum      mean sum      mean sum
index
A      3.000000   6  7.500000  15  7.000000  14
B      2.666667   8  3.666667  11  4.333333  13
C      6.000000  18  6.333333  19  1.000000   3
D      4.250000  17  3.250000  13  5.000000  20
E      2.333333   7  1.666667   5  1.333333   4

In [47]:
import pandas as pd

period = pd.period_range(
    start='2022-01-13 00:00:00',
    end='2022-01-13 02:30:00',
    freq='30min'
)

data = {
    "col1": [1, 2, 3, 4, 5, 6],
    "col2": period
}

idx = ["row1", "row2", "row3", "row4", "row5", "row6"]

df = pd.DataFrame(data, index=idx)
df

      col1              col2
row1     1  2022-01-13 00:00
row2     2  2022-01-13 00:30
row3     3  2022-01-13 01:00
row4     4  2022-01-13 01:30
row5     5  2022-01-13 02:00
row6     6  2022-01-13 02:30

In [48]:
df.rolling(window=3).sum(numeric_only=True)  # rolling이란 어떤 기간을 주고 그 걸 두하는 방식
# window = 3이란 데이터 3개를 가지고 구해라 이기 때문에 앞에 두개는 인식이 안된다
# 그렇기 때문에 앞에 2 값은 데이터가 NaN으로 출력된다.

      col1
row1   NaN
row2   NaN
row3   6.0
row4   9.0
row5  12.0
row6  15.0

In [49]:
df.rolling(window=3).mean(numeric_only=True) 
# 이러한 것들은 주식같은 데이터에서 사용될 수 있다

      col1
row1   NaN
row2   NaN
row3   2.0
row4   3.0
row5   4.0
row6   5.0

-----------------------------
## DataFrame 열과 행 인덱싱

In [50]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9611482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473999],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}

column_list = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index_list = ["서울", "부산", "인천", "대구"]

df = pd.DataFrame(data, index=index_list, columns=column_list)
df

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9611482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473999         0.0141

In [51]:
df.values

array([['수도권', 9904312, 9611482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473999, 0.0141]], dtype=object)

In [52]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='str')

In [53]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='str')

In [54]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473999         0.0141

In [55]:
df.T

도시                  서울       부산       인천       대구
특성
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9611482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473999
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [56]:
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [57]:
# 열을 먼저 작성하고 행을 작성해야한다 
df["서울"] # 오류남

KeyError: '서울'

In [58]:
df.지역 # 컬럼 명을 적을때 공백이 있으면 사용이 안되기 때문에 공백을 적지 말자

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: str

In [59]:
df[["2010", "2015"]]

특성     2010     2015
도시
서울  9611482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [60]:
df[["지역"]]

특성   지역
도시
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [61]:
type(df[["지역"]])
type(df["지역"])

pandas.Series

In [62]:
import numpy as np

df2 = pd.DataFrame(np.arange(12).reshape(3, 4))   # np.arange() & range()함수는 동일하게 동작한다
# reshape은 numpy에서 구조를 변경할 때 사용한다.

df2

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [63]:
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473999           1.41

In [64]:
df["2005-2010 증가율"] = ((df["2010"] - df["2005"] )/ df["2005"] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972           2.83          -1.55
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473999           1.41          -0.99

In [65]:
del df["2010-2015 증가율"] # df.drop("2010-2015 증가율", axis=1)
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473999          -0.99

In [66]:
df3  = df.drop("2005-2010 증가율", axis=1)
df3

특성   지역     2015     2010     2005     2000
도시
서울  수도권  9904312  9611482  9762546  9853972
부산  경상권  3448737  3393191  3512547  3655437
인천  수도권  2890451  2632035  2517680  2466338
대구  경상권  2466052  2431774  2456016  2473999

In [67]:
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473999          -0.99

In [68]:
df3  = df.drop("서울", axis=0)
df3

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473999          -0.99

In [69]:
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473999          -0.99

In [70]:
df["2015"]["서울"]

np.int64(9904312)

In [71]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55

In [72]:
df[1:3]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [73]:
df["서울":"부산"]  # 슬라이싱

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [74]:
df[:2]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [75]:
df.iloc[[0,2]] # 해당하는 값을 찾고

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [76]:
df.iloc[0:2] # 범위에 있는 값을 찾는다

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [77]:
df.loc["서울": "부산"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [78]:
df.loc[["서울","부산"]]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시
서울  수도권  9904312  9611482  9762546  9853972          -1.55
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [79]:
df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [80]:
df.iloc[0]  # iloc(), loc() 함수를 사용하면 행-렬 순서로 사용된다.
# 지금과 같이 행으로 나온다.

A    1
B    2
C    3
Name: 0, dtype: int64

In [81]:
df.iloc[[0,2]] # 이것도한 마찬가지로 행-렬 순서로 데이터를 출력한다.

   A  B  C
0  1  2  3
2  7  8  9

In [82]:
df.loc[0]  # 지금 위치 인덱스가 아니라 열 정수의 이름을 넣은 것이다. 한마디로 라벨명이다.

A    1
B    2
C    3
Name: 0, dtype: int64

In [83]:
df.loc[:,"A"]  # 이것또한 행-렬 순서이다. 꼭 기억해야함!!

0    1
1    4
2    7
Name: A, dtype: int64

In [84]:
# 이 함수들을 사용하면 행-렬 함수다
df.loc[:,"A":"B"]  # 열이 2개이다 열이 1개이면 시리즈로 2개이면 데이터 프레임으로 자동으로 만들어진다

   A  B
0  1  2
1  4  5
2  7  8

In [85]:
df["A"] # 이렇게 직접 접근하면 열-행의 순서로 기술 해야한다.

0    1
1    4
2    7
Name: A, dtype: int64

In [86]:
df.loc[0]["B"]

np.int64(2)

In [87]:
df["B"][0]
# 위 두개를 보면 같은 값을 참조한다.

np.int64(2)

이 내용이 진짜 중요함!!

iloc(), loc() 함수를 사용하면 행-열 순서이고 
직접 참조를 하면 열-행 순서이다

꼭 기억하기!!

In [88]:
import pandas as pd
import numpy as np
df = pd.DataFrame(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    index=["row1", "row2", "row3"],
    columns=["col1", "col2", "col3"]
)

print(df)

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [89]:
reslut = df.loc["row1"]
reslut

col1    1
col2    2
col3    3
Name: row1, dtype: int64

In [90]:
bool2 = [False, True, False]
reslut = df.loc[bool2]
reslut

      col1  col2  col3
row2     4     5     6

In [91]:
reslut = df.loc[df['col3'] > 5]
reslut

      col1  col2  col3
row2     4     5     6
row3     7     8     9

In [92]:
reslut = df.loc[df['col3'] > 5, ['col2']]
reslut

      col2
row2     5
row3     8

In [93]:
result = df.loc[lambda df: df['col2'] == 5]
result

      col1  col2  col3
row2     4     5     6

In [94]:
df.loc[['row1','row2','row3']] = 10
df

      col1  col2  col3
row1    10    10    10
row2    10    10    10
row3    10    10    10

In [95]:
df.loc[:,'col3'] = 'B'
df

TypeError: Invalid value 'B' for dtype 'int64'

In [ ]:
index_tuples = [('row1', 'val1'), ('row1', 'val2'), ('row2', 'val1'), ('row2', 'val2'),
                ('row2', 'val3'), ('row3', 'val2'), ('row3', 'val3')]

values = [[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18], [19,20,21]]
index = pd.MultiIndex.from_tuples(index_tuples)  # 인덱스 설정
df = pd.DataFrame(values, columns=['col1', 'col2', 'col3'], index = index)
df

In [ ]:
reslut = df.loc["row2"]
reslut

In [ ]:
reslut = df.loc[("row2", "val2")]
reslut

In [96]:
reslut = df.loc[[("row2", "val2")]]
reslut

KeyError: "None of [Index([('row2', 'val2')], dtype='object')] are in the [index]"

In [97]:
reslut = df.loc[("row2", "val2"), "col3"]
reslut

AssertionError:

In [98]:
reslut = df.loc[("row1", "val2"): ("row2", "val2")]
reslut

AssertionError: Start slice bound is non-scalar

In [99]:
import pandas as pd
data = [
    [100, 900, 800, 700],
    [1200, 1400, 900, 800]
]
columns = [
    ['영업이익', '영업이익', '당기순이익', '당기순이익'],
    ['컨센서스', '잠정치', '컨센서스', '잠정치']
]
index = ["2020/06", "2020/09"]
df = pd.DataFrame(data=data, index=index, columns=columns)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [100]:
import pandas as pd
data = [
    [100, 900, 800, 700],
    [1200, 1400, 900, 800]
]
index = ["2020/06", "2020/09"]
level_0 = ["영업이익", "당기순이익"]
level_1 = ["컨센서스", "잠정치"]
idx = pd.MultiIndex.from_product([level_0, level_1])
df = pd.DataFrame(data=data, index=index, columns=idx)
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [101]:
import io
import pandas as pd

csv = '''
	A팀		B팀		C팀	
	삼성전자	카카오	삼성전자	카카오	삼성전자	카카오
2023-08-14	10	20	30	40	50	60
2023-08-16	20	20	30	40	50	60
2023-08-17	30	40	10	20	50	60
2023-08-18	30	40	10	20	50	60
2023-08-21	30	40	30	40	30	40
'''

df_csv = pd.read_csv(io.StringIO(csv), sep='\t', index_col=0, header=[0, 1])
df_csv

,A팀,Unnamed: 2_level_0,B팀,Unnamed: 4_level_0,C팀,Unnamed: 6_level_0
,삼성전자,카카오,삼성전자,카카오,삼성전자,카카오
2023-08-14,10,20,30,40,50,60
2023-08-16,20,20,30,40,50,60
2023-08-17,30,40,10,20,50,60
2023-08-18,30,40,10,20,50,60
2023-08-21,30,40,30,40,30,40

In [102]:
import io
import pandas as pd

csv = '''\tA팀\tA팀\tB팀\tB팀\tC팀\tC팀
\t삼성전자\t카카오\t삼성전자\t카카오\t삼성전자\t카카오
2023-08-14\t10\t20\t30\t40\t50\t60
2023-08-16\t20\t20\t30\t40\t50\t60
2023-08-17\t30\t40\t10\t20\t50\t60
2023-08-18\t30\t40\t10\t20\t50\t60
2023-08-21\t30\t40\t30\t40\t30\t40
'''

df_csv = pd.read_csv(io.StringIO(csv), sep='\t', index_col=0, header=[0, 1])
df_csv

             A팀       B팀       C팀
           삼성전자 카카오 삼성전자 카카오 삼성전자 카카오
2023-08-14   10  20   30  40   50  60
2023-08-16   20  20   30  40   50  60
2023-08-17   30  40   10  20   50  60
2023-08-18   30  40   10  20   50  60
2023-08-21   30  40   30  40   30  40

In [103]:
df1 = df_csv.columns.to_frame(index=False).apply(lambda x: x.mask(x.str.contains('Unnamed'))).ffill()
df_csv = df_csv.set_axis(pd.MultiIndex.from_frame(df1, names=[''] * len(df_csv.columns[0])), axis=1)
df_csv

             A팀       B팀       C팀
           삼성전자 카카오 삼성전자 카카오 삼성전자 카카오
2023-08-14   10  20   30  40   50  60
2023-08-16   20  20   30  40   50  60
2023-08-17   30  40   10  20   50  60
2023-08-18   30  40   10  20   50  60
2023-08-21   30  40   30  40   30  40

In [104]:
df

         영업이익       당기순이익
         컨센서스   잠정치  컨센서스  잠정치
2020/06   100   900   800  700
2020/09  1200  1400   900  800

In [105]:
df["영업이익"]

         컨센서스   잠정치
2020/06   100   900
2020/09  1200  1400

In [106]:
df[[("영업이익","컨센서스")]]

         영업이익
         컨센서스
2020/06   100
2020/09  1200

In [107]:
df.loc["2020/06", "영업이익"]

컨센서스    100
잠정치     900
Name: 2020/06, dtype: int64

In [108]:
df.loc[["2020/06"], ["영업이익"]]

        영업이익
        컨센서스  잠정치
2020/06  100  900

In [109]:
df.loc["2020/06",( "영업이익", "컨센서스")]

np.int64(100)

In [110]:
df.loc["2020/06",(slice(None), "컨센서스")]
# : 슬라이스와 동일한 의미, 멀티 인덱스의 특정 레벨 내의 모든 값

영업이익   컨센서스    100
당기순이익  컨센서스    800
Name: 2020/06, dtype: int64

In [111]:
df.loc[["2020/06"],(slice(None), "컨센서스")]

        영업이익 당기순이익
        컨센서스  컨센서스
2020/06  100   800

In [112]:
df2 = df.T
df2

            2020/06  2020/09
영업이익  컨센서스      100     1200
      잠정치       900     1400
당기순이익 컨센서스      800      900
      잠정치       700      800

In [113]:
df2.loc[[("영업이익", "컨센서스" )]]

           2020/06  2020/09
영업이익 컨센서스      100     1200

In [114]:
df2.loc[("영업이익", "컨센서스" ), "2020/06"]

np.int64(100)

In [115]:
df2.loc[[("영업이익", "컨센서스" )], "2020/06"]

영업이익  컨센서스    100
Name: 2020/06, dtype: int64

In [116]:
df2.loc[[("영업이익", "컨센서스" )], ["2020/06"]]

           2020/06
영업이익 컨센서스      100

In [117]:
df2.loc[(slice(None), "컨센서스" ),:]

            2020/06  2020/09
영업이익  컨센서스      100     1200
당기순이익 컨센서스      800      900

In [118]:
col1 = [1, 2, 3, 4, 5]
col2 = ['one', 'two', 'three', 'four', 'five']
col3 = [1.5, 2.5, 3.5, 4.5, 5.5]
col4 = [True, False, False, True, True]
df = pd.DataFrame({"col1": col1, "col2": col2, "col3": col3, "col4": col4})
df

   col1   col2  col3   col4
0     1    one   1.5   True
1     2    two   2.5  False
2     3  three   3.5  False
3     4   four   4.5   True
4     5   five   5.5   True

In [119]:
df.dtypes

col1      int64
col2        str
col3    float64
col4       bool
dtype: object

In [120]:
result = df.select_dtypes(include=['bool', 'float'])
result

   col3   col4
0   1.5   True
1   2.5  False
2   3.5  False
3   4.5   True
4   5.5   True

In [121]:
reslut = df.select_dtypes(exclude=['int64'])

In [122]:
reslut

    col2  col3   col4
0    one   1.5   True
1    two   2.5  False
2  three   3.5  False
3   four   4.5   True
4   five   5.5   True

In [123]:
col = ['alpha', 'beta', 'gamma', 'delta', 'epsilon']
row = ['sigma', 'omega', 'lambda']
data = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

df = pd.DataFrame(data,row,col)
df

        alpha  beta  gamma  delta  epsilon
sigma       1     2      3      4        5
omega       6     7      8      9       10
lambda     11    12     13     14       15

In [124]:
df.filter(items=['alpha','delta'])

        alpha  delta
sigma       1      4
omega       6      9
lambda     11     14

In [125]:
df.filter(items=['omega'],axis=0)

       alpha  beta  gamma  delta  epsilon
omega      6     7      8      9       10

In [126]:
df.filter(like='ta')

        beta  delta
sigma      2      4
omega      7      9
lambda    12     14

In [127]:
df.filter(regex='[mn]')

        gamma  epsilon
sigma       3        5
omega       8       10
lambda     13       15

In [128]:
df.filter(regex='^g')

        gamma
sigma       3
omega       8
lambda     13

In [129]:
df.filter(regex='a$')

        alpha  beta  gamma  delta
sigma       1     2      3      4
omega       6     7      8      9
lambda     11    12     13     14

In [131]:
import pandas as dp

df = pd.read_csv('./titanic/train.csv')
df.iloc[0:5, 1:4]

   Survived  Pclass                                               Name
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

In [132]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [134]:
df[["Name", "Age", "Sex", "Survived"]]

                                                  Name   Age     Sex  Survived
0                              Braund, Mr. Owen Harris  22.0    male         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female         1
2                               Heikkinen, Miss. Laina  26.0  female         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female         1
4                             Allen, Mr. William Henry  35.0    male         0
..                                                 ...   ...     ...       ...
886                              Montvila, Rev. Juozas  27.0    male         0
887                       Graham, Miss. Margaret Edith  19.0  female         1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female         0
889                              Behr, Mr. Karl Howell  26.0    male         1
890                                Dooley, Mr. Patrick  32.0    male         0

[891 rows x 4 columns]

In [137]:
mask = (df['Sex'] == "female")
mask

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [138]:
df[mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [139]:
df9 = df[df['PassengerId'] == 3]['Name']
df9

2    Heikkinen, Miss. Laina
Name: Name, dtype: str

In [140]:
df9.values

<StringArray>
['Heikkinen, Miss. Laina']
Length: 1, dtype: str

In [143]:
df['family'] = df['SibSp'] + df['Parch']
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1

-------------------------------
## 인덱스 활용

In [144]:
df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [145]:
df = df.set_index('A')
df

   B  C
A
1  2  3
4  5  6
7  8  9

## 행 추가

In [150]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns=[48, 49, 50])
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9

In [149]:
a = pd.DataFrame(data = [[1,2,3]], columns=[48,49,50])
a

   48  49  50
0   1   2   3

In [157]:
df = pd.concat([df, a])
df

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
0   1   2   3
0   1   2   3

In [155]:
import pandas as pd
print(pd.__version__)

3.0.1

In [158]:
df2 = df.reset_index(drop = True)
df2

   48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
3   1   2   3
4   1   2   3

In [159]:
df2 = df.reset_index(drop = False)
df2

   index  48  49  50
0      0   1   2   3
1      1   4   5   6
2      2   7   8   9
3      0   1   2   3
4      0   1   2   3

---------------------
## 인덱스 컬럼 데이터 삭제

In [174]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns=["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [175]:
df2 = df.drop('A', axis = 1, inplace=False)

In [176]:
df2

   B  C
0  2  3
1  5  6
2  8  9

In [177]:
df.drop('B', axis = 1)
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [178]:
df.drop(2, axis=0, inplace=True)
df

   A  B  C
0  1  2  3
1  4  5  6

In [184]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns=["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [191]:
df2 = df.drop([0,2], axis=0, inplace=False)
df2

   A  B  C
1  4  5  6

In [190]:
df2=df.drop(["A","C"], axis=1, inplace=False)
df2

   B
0  2
1  5
2  8

In [195]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [40, 50, 60], [23, 35, 37]]),
                  index=[2.5, 12.6, 4.8, 4.8, 2.5],
                  columns=[48, 49, 50])

df

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8   40  50  60
2.5   23  35  37

In [196]:
df = df.reset_index()
df

   index  48  49  50
0    2.5   1   2   3
1   12.6   4   5   6
2    4.8   7   8   9
3    4.8  40  50  60
4    2.5  23  35  37

In [197]:
df2 = df.drop_duplicates(subset="index", keep = 'last').set_index('index')
df2

       48  49  50
index
12.6    4   5   6
4.8    40  50  60
2.5    23  35  37

In [199]:
df2 = df.drop_duplicates(subset="index", keep = 'first').set_index('index')
df2

       48  49  50
index
2.5     1   2   3
12.6    4   5   6
4.8     7   8   9

In [201]:
df2 = df.drop_duplicates(subset="index", keep = False).set_index('index')
df2

       48  49  50
index
12.6    4   5   6

In [202]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns=["A", "B", "C"], index=[11,22,33])
df

    A  B  C
11  1  2  3
22  4  5  6
33  7  8  9

In [203]:
df.index[1]

np.int64(22)

In [204]:
df2 = df.drop(df.index[1])
df2

    A  B  C
11  1  2  3
33  7  8  9

In [205]:
df2 = df.drop(22)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [206]:
df2 = df.drop(df.index[1] , axis=0)
df2

    A  B  C
11  1  2  3
33  7  8  9

In [207]:
col = ['col1', 'col2', 'col3', 'col4', 'col5']
row = ['row1', 'row2', 'row3', 'row4']
data = [[1,2,3,pd.NA,5],[6,pd.NA,8,pd.NA,10],[11,12,13,14,15],[pd.NA,pd.NA,pd.NA,pd.NA,pd.NA]]

df = pd.DataFrame(data,row,col)
df

      col1  col2  col3  col4  col5
row1     1     2     3  <NA>     5
row2     6  <NA>     8  <NA>    10
row3    11    12    13    14    15
row4  <NA>  <NA>  <NA>  <NA>  <NA>

In [208]:
df2 = df.dropna(axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [209]:
df2 = df.dropna(axis=1)
df2

Empty DataFrame
Columns: []
Index: [row1, row2, row3, row4]

In [210]:
df2 = df.dropna(how = 'any', axis=0)
df2

     col1 col2 col3 col4 col5
row3   11   12   13   14   15

In [211]:
df2 = df.dropna(how = 'all', axis=0)
df2

     col1  col2 col3  col4 col5
row1    1     2    3  <NA>    5
row2    6  <NA>    8  <NA>   10
row3   11    12   13    14   15

In [212]:
df2 = df.dropna(thresh=3)
df2

     col1  col2 col3  col4 col5
row1    1     2    3  <NA>    5
row2    6  <NA>    8  <NA>   10
row3   11    12   13    14   15

In [213]:
df2 = df.dropna(thresh=4)
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [214]:
df2 = df.dropna(subset=["col1","col2"])
df2

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [216]:
df.dropna(subset=["col1","col2"], inplace=True)

In [217]:
df

     col1 col2 col3  col4 col5
row1    1    2    3  <NA>    5
row3   11   12   13    14   15

In [218]:
col = ['col1', 'col2', 'col3', 'col4', 'col5']
row = ['row1', 'row2', 'row3', 'row4', 'row5']
na = np.nan

data = [[na, 2, na, 4, na],
        [6, 7, na, 9, na],
        [11, na, na, 14, 15],
        [na, 17, na, na, 20],
        [na, 22, na, na, 25]]

df = pd.DataFrame(data, row, col)
df

      col1  col2  col3  col4  col5
row1   NaN   2.0   NaN   4.0   NaN
row2   6.0   7.0   NaN   9.0   NaN
row3  11.0   NaN   NaN  14.0  15.0
row4   NaN  17.0   NaN   NaN  20.0
row5   NaN  22.0   NaN   NaN  25.0

In [219]:
df.fillna("A")

      col1  col2 col3  col4  col5
row1     A   2.0    A   4.0     A
row2   6.0   7.0    A   9.0     A
row3  11.0     A    A  14.0  15.0
row4     A  17.0    A     A  20.0
row5     A  22.0    A     A  25.0

In [220]:
dict = {'col1':'A', 'col2':'B', 'col3':'C', 'col4':'D', 'col5':'E'}
df.fillna(value=dict)

      col1  col2 col3  col4  col5
row1     A   2.0    C   4.0     E
row2   6.0   7.0    C   9.0     E
row3  11.0     B    C  14.0  15.0
row4     A  17.0    C     D  20.0
row5     A  22.0    C     D  25.0

In [221]:
df

      col1  col2  col3  col4  col5
row1   NaN   2.0   NaN   4.0   NaN
row2   6.0   7.0   NaN   9.0   NaN
row3  11.0   NaN   NaN  14.0  15.0
row4   NaN  17.0   NaN   NaN  20.0
row5   NaN  22.0   NaN   NaN  25.0

In [222]:
df["col1"].fillna(100)

row1    100.0
row2      6.0
row3     11.0
row4    100.0
row5    100.0
Name: col1, dtype: float64

---------------
## merge() 에 대해서

In [224]:
df1 = pd.DataFrame({'고객번호': [1001, 1002, 1003, 1004, 1005, 1006, 1007],
                    '이름': ['둘리', '도우너', '또치', '길동', '희동', '마이콜', '영희']},
                   columns=['고객번호', '이름'])

df1

   고객번호   이름
0  1001   둘리
1  1002  도우너
2  1003   또치
3  1004   길동
4  1005   희동
5  1006  마이콜
6  1007   영희

In [225]:
df2 = pd.DataFrame({'고객번호': [1001, 1001, 1005, 1006, 1008, 1001],
                    '금액': [10000, 20000, 15000, 5000, 100000, 30000]},
                   columns=['고객번호', '금액'])

df2

   고객번호      금액
0  1001   10000
1  1001   20000
2  1005   15000
3  1006    5000
4  1008  100000
5  1001   30000

In [226]:
df3 = pd.merge(df1, df2)
df3

   고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

In [231]:
df4 = pd.merge(df1, df2, how= "outer")
df4

   고객번호   이름        금액
0  1001   둘리   10000.0
1  1001   둘리   20000.0
2  1001   둘리   30000.0
3  1002  도우너       NaN
4  1003   또치       NaN
5  1004   길동       NaN
6  1005   희동   15000.0
7  1006  마이콜    5000.0
8  1007   영희       NaN
9  1008  NaN  100000.0

In [232]:
df5 = pd.merge(df1, df2, how= "left")
df5

   고객번호   이름       금액
0  1001   둘리  10000.0
1  1001   둘리  20000.0
2  1001   둘리  30000.0
3  1002  도우너      NaN
4  1003   또치      NaN
5  1004   길동      NaN
6  1005   희동  15000.0
7  1006  마이콜   5000.0
8  1007   영희      NaN

In [233]:
df6 = pd.merge(df1, df2, how= "right")
df6

   고객번호   이름      금액
0  1001   둘리   10000
1  1001   둘리   20000
2  1005   희동   15000
3  1006  마이콜    5000
4  1008  NaN  100000
5  1001   둘리   30000

In [234]:
df1 = pd.DataFrame({
    '품종': ['setosa', 'setosa', 'virginica', 'virginica'],
    '꽃잎길이': [1.4, 1.3, 1.5, 1.3]},
    columns=['품종', '꽃잎길이'])

df1

          품종  꽃잎길이
0     setosa   1.4
1     setosa   1.3
2  virginica   1.5
3  virginica   1.3

In [235]:
df2 = pd.DataFrame({
    '품종': ['setosa', 'virginica', 'virginica', 'versicolor'],
    '꽃잎너비': [0.4, 0.3, 0.5, 0.3]},
    columns=['품종', '꽃잎너비'])

df2

           품종  꽃잎너비
0      setosa   0.4
1   virginica   0.3
2   virginica   0.5
3  versicolor   0.3

In [236]:
df3 = pd.merge(df1, df2)

In [237]:
df3

          품종  꽃잎길이  꽃잎너비
0     setosa   1.4   0.4
1     setosa   1.3   0.4
2  virginica   1.5   0.3
3  virginica   1.5   0.5
4  virginica   1.3   0.3
5  virginica   1.3   0.5

In [238]:
df1 = pd.DataFrame({
    '고객명': ['춘향', '춘향', '몽룡'],
    '날짜': ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터': ['20000', '30000', '100000']})

df1

  고객명          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [239]:
df2 = pd.DataFrame({
    '고객명': ['춘향', '몽룡'],
    '데이터': ['여자', '남자']})

df2

  고객명 데이터
0  춘향  여자
1  몽룡  남자

In [240]:
df3 = pd.merge(df1, df2, on= "고객명")
df3

  고객명          날짜   데이터_x 데이터_y
0  춘향  2018-01-01   20000    여자
1  춘향  2018-01-02   30000    여자
2  몽룡  2018-01-01  100000    남자

In [241]:
df1 = pd.DataFrame({
    '이름': ['춘향', '춘향', '몽룡'],
    '날짜': ['2018-01-01', '2018-01-02', '2018-01-01'],
    '데이터': ['20000', '30000', '100000']})

df1

   이름          날짜     데이터
0  춘향  2018-01-01   20000
1  춘향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [242]:
df2 = pd.DataFrame({
    '성명': ['춘향', '몽룡'],
    '데이터': ['여자', '남자']})

df2

   성명 데이터
0  춘향  여자
1  몽룡  남자

In [243]:
df3 = pd.merge(df1, df2, left_on="이름", right_on="성명")
df3

   이름          날짜   데이터_x  성명 데이터_y
0  춘향  2018-01-01   20000  춘향    여자
1  춘향  2018-01-02   30000  춘향    여자
2  몽룡  2018-01-01  100000  몽룡    남자

In [244]:
df1 = pd.DataFrame({'도시': ['서울', '서울', '서울', '부산', '부산'],
                    '연도': [2000, 2005, 2010, 2000, 2005],
                    '인구': [9853972, 9762546, 9631482, 3655437, 3512547]})

df1

   도시    연도       인구
0  서울  2000  9853972
1  서울  2005  9762546
2  서울  2010  9631482
3  부산  2000  3655437
4  부산  2005  3512547

In [245]:
df2 = pd.DataFrame(np.arange(12).reshape((6, 2)),
                   index=[['부산', '부산', '서울', '서울', '서울', '서울'],
                          [2000, 2005, 2000, 2005, 2010, 2015]],
                   columns=['데이터1', '데이터2'])

df2

         데이터1  데이터2
부산 2000     0     1
   2005     2     3
서울 2000     4     5
   2005     6     7
   2010     8     9
   2015    10    11

In [248]:
df3 = pd.merge(df1, df2, left_on=["도시","연도"], right_index=True)
df3

   도시    연도       인구  데이터1  데이터2
0  서울  2000  9853972     4     5
1  서울  2005  9762546     6     7
2  서울  2010  9631482     8     9
3  부산  2000  3655437     0     1
4  부산  2005  3512547     2     3

In [249]:
df1 = pd.DataFrame(
    [[1., 2.], [3., 4.], [5., 6.]],
    index=['a', 'c', 'e'],
    columns=['서울', '부산'])

df1

    서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [250]:
df2 = pd.DataFrame(
    [[7., 8.], [9., 10.], [11., 12.], [13, 14]],
    index=['b', 'c', 'd', 'e'],
    columns=['대구', '광주'])

df2

     대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [251]:
df3 = pd.merge(df1, df2,how="outer" ,left_index=True, right_index=True)
df3

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [252]:
df3 = pd.merge(df1, df2,left_index=True, right_index=True)
df3

    서울   부산    대구    광주
c  3.0  4.0   9.0  10.0
e  5.0  6.0  13.0  14.0

-------------------
## concat()

In [1]:
import pandas as pd

s1 = pd.Series([0,1], index = ["A", "B"])
s1

A    0
B    1
dtype: int64

In [2]:
s2 = pd.Series([2, 3, 4], index = ["A", "B", "C"])
s2

A    2
B    3
C    4
dtype: int64

In [3]:
s3 = pd.concat([s1, s2])
s3

A    0
B    1
A    2
B    3
C    4
dtype: int64

In [4]:
s3 = pd.concat([s1, s2], axis = 1)
s3

     0  1
A  0.0  2
B  1.0  3
C  NaN  4

In [6]:
import numpy as np

In [7]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2),
                   index=['a', 'b', 'c'],
                   columns=['데이터1', '데이터2'])
df1

   데이터1  데이터2
a     0     1
b     2     3
c     4     5

In [8]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2),
                   index=['a', 'c'],
                   columns=['데이터3', '데이터4'])
df2

   데이터3  데이터4
a     5     6
c     7     8

In [10]:
df3 = pd.concat([df1, df2], axis=1)
df3

   데이터1  데이터2  데이터3  데이터4
a     0     1   5.0   6.0
b     2     3   NaN   NaN
c     4     5   7.0   8.0

In [11]:
df3 = pd.concat([df1, df2], axis=0)
df3

   데이터1  데이터2  데이터3  데이터4
a   0.0   1.0   NaN   NaN
b   2.0   3.0   NaN   NaN
c   4.0   5.0   NaN   NaN
a   NaN   NaN   5.0   6.0
c   NaN   NaN   7.0   8.0

In [15]:
df1 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                   index=['a', 'c', 'e'],
                   columns=['서울', '부산'])
df1

    서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [16]:
df2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                   index=['b', 'c', 'd', 'e'],
                   columns=['대구', '광주'])
df2

     대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [17]:
df3 = df1.join(df2, how= 'outer')
df3

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [18]:
df4 = df1.join(df2, how= 'inner')
df4

    서울   부산    대구    광주
c  3.0  4.0   9.0  10.0
e  5.0  6.0  13.0  14.0

In [19]:
df5 = df1.join(df2, how= 'right')
df5

    서울   부산    대구    광주
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [21]:
import numpy as np

n = np.nan
idx = ['row1', 'row2', 'row3']
col = ['col1', 'col2', 'col3']
data = [[1, 2, 200], [100, 5, 6], [7, 300, n]]
df = pd.DataFrame(data, idx, col)
df

      col1  col2   col3
row1     1     2  200.0
row2   100     5    6.0
row3     7   300    NaN

In [22]:
df.idxmax(axis=0)   # 최대값이 포함된 행 또는 열

col1    row2
col2    row3
col3    row1
dtype: str

In [23]:
df.idxmax(axis=1)

row1    col3
row2    col1
row3    col2
dtype: str

In [24]:
df.idxmin(axis=0, skipna=True)

col1    row1
col2    row1
col3    row2
dtype: str

In [25]:
df.idxmin(axis=1)

row1    col1
row2    col2
row3    col1
dtype: str

----------------
## 시계열 데이터

In [27]:
data_str = ["2018, 1, 1", "2018, 1, 4", "2018, 1, 5"]
idx = pd.to_datetime(data_str)
idx

DatetimeIndex(['2018-01-01', '2018-01-04', '2018-01-05'], dtype='datetime64[us]', freq=None)

In [29]:
np.random.seed(0)
s = pd.Series(np.random.rand(3), index=idx)
s

2018-01-01    0.548814
2018-01-04    0.715189
2018-01-05    0.602763
dtype: float64

In [30]:
pd.date_range("2020-7-1", "2020-7-30")

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30'],
              dtype='datetime64[us]', freq='D')

In [31]:
pd.date_range(start = "2020-7-1",end =  "2020-7-30")

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30'],
              dtype='datetime64[us]', freq='D')

In [32]:
pd.date_range(start = "2020-7-1", periods= 7, freq="s")

DatetimeIndex(['2020-07-01 00:00:00', '2020-07-01 00:00:01',
               '2020-07-01 00:00:02', '2020-07-01 00:00:03',
               '2020-07-01 00:00:04', '2020-07-01 00:00:05',
               '2020-07-01 00:00:06'],
              dtype='datetime64[us]', freq='s')

In [34]:
pd.date_range("2026-1-1", "2026-12-31", freq="W")

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08', '2026-02-15', '2026-02-22',
               '2026-03-01', '2026-03-08', '2026-03-15', '2026-03-22',
               '2026-03-29', '2026-04-05', '2026-04-12', '2026-04-19',
               '2026-04-26', '2026-05-03', '2026-05-10', '2026-05-17',
               '2026-05-24', '2026-05-31', '2026-06-07', '2026-06-14',
               '2026-06-21', '2026-06-28', '2026-07-05', '2026-07-12',
               '2026-07-19', '2026-07-26', '2026-08-02', '2026-08-09',
               '2026-08-16', '2026-08-23', '2026-08-30', '2026-09-06',
               '2026-09-13', '2026-09-20', '2026-09-27', '2026-10-04',
               '2026-10-11', '2026-10-18', '2026-10-25', '2026-11-01',
               '2026-11-08', '2026-11-15', '2026-11-22', '2026-11-29',
               '2026-12-06', '2026-12-13', '2026-12-20', '2026-12-27'],
              dtype='datetime64[us]', freq='W-SUN')

In [36]:
pd.date_range("2026-1-1", "2026-12-31", freq="W-FRI")

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06', '2026-02-13', '2026-02-20',
               '2026-02-27', '2026-03-06', '2026-03-13', '2026-03-20',
               '2026-03-27', '2026-04-03', '2026-04-10', '2026-04-17',
               '2026-04-24', '2026-05-01', '2026-05-08', '2026-05-15',
               '2026-05-22', '2026-05-29', '2026-06-05', '2026-06-12',
               '2026-06-19', '2026-06-26', '2026-07-03', '2026-07-10',
               '2026-07-17', '2026-07-24', '2026-07-31', '2026-08-07',
               '2026-08-14', '2026-08-21', '2026-08-28', '2026-09-04',
               '2026-09-11', '2026-09-18', '2026-09-25', '2026-10-02',
               '2026-10-09', '2026-10-16', '2026-10-23', '2026-10-30',
               '2026-11-06', '2026-11-13', '2026-11-20', '2026-11-27',
               '2026-12-04', '2026-12-11', '2026-12-18', '2026-12-25'],
              dtype='datetime64[us]', freq='W-FRI')

In [39]:
pd.date_range("2026-1-1", "2026-12-31", freq="B")

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-05', '2026-01-06',
               '2026-01-07', '2026-01-08', '2026-01-09', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01-19', '2026-01-20', '2026-01-21', '2026-01-22',
               '2026-01-23', '2026-01-26', '2026-01-27', '2026-01-28',
               '2026-01-29', '2026-01-30', '2026-02-02', '2026-02-03',
               '2026-02-04', '2026-02-05', '2026-02-06', '2026-02-09',
               '2026-02-10', '2026-02-11', '2026-02-12', '2026-02-13',
               '2026-02-16', '2026-02-17', '2026-02-18', '2026-02-19',
               '2026-02-20', '2026-02-23', '2026-02-24', '2026-02-25',
               '2026-02-26', '2026-02-27', '2026-03-02', '2026-03-03',
               '2026-03-04', '2026-03-05', '2026-03-06', '2026-03-09',
               '2026-03-10', '2026-03-11', '2026-03-12', '2026-03-13',
               '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19',
               '2026-03-20', '2026-03-23', '2026-03-24', '2026-03-25',
               '2026-03-26', '2026-03-27', '2026-03-30', '2026-03-31',
               '2026-04-01', '2026-04-02', '2026-04-03', '2026-04-06',
               '2026-04-07', '2026-04-08', '2026-04-09', '2026-04-10',
               '2026-04-13', '2026-04-14', '2026-04-15', '2026-04-16',
               '2026-04-17', '2026-04-20', '2026-04-21', '2026-04-22',
               '2026-04-23', '2026-04-24', '2026-04-27', '2026-04-28',
               '2026-04-29', '2026-04-30', '2026-05-01', '2026-05-04',
               '2026-05-05', '2026-05-06', '2026-05-07', '2026-05-08',
               '2026-05-11', '2026-05-12', '2026-05-13', '2026-05-14',
               '2026-05-15', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22', '2026-05-25', '2026-05-26',
               '2026-05-27', '2026-05-28', '2026-05-29', '2026-06-01',
               '2026-06-02', '2026-06-03', '2026-06-04', '2026-06-05',
               '2026-06-08', '2026-06-09', '2026-06-10', '2026-06-11',
               '2026-06-12', '2026-06-15', '2026-06-16', '2026-06-17',
               '2026-06-18', '2026-06-19', '2026-06-22', '2026-06-23',
               '2026-06-24', '2026-06-25', '2026-06-26', '2026-06-29',
               '2026-06-30', '2026-07-01', '2026-07-02', '2026-07-03',
               '2026-07-06', '2026-07-07', '2026-07-08', '2026-07-09',
               '2026-07-10', '2026-07-13', '2026-07-14', '2026-07-15',
               '2026-07-16', '2026-07-17', '2026-07-20', '2026-07-21',
               '2026-07-22', '2026-07-23', '2026-07-24', '2026-07-27',
               '2026-07-28', '2026-07-29', '2026-07-30', '2026-07-31',
               '2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06',
               '2026-08-07', '2026-08-10', '2026-08-11', '2026-08-12',
               '2026-08-13', '2026-08-14', '2026-08-17', '2026-08-18',
               '2026-08-19', '2026-08-20', '2026-08-21', '2026-08-24',
               '2026-08-25', '2026-08-26', '2026-08-27', '2026-08-28',
               '2026-08-31', '2026-09-01', '2026-09-02', '2026-09-03',
               '2026-09-04', '2026-09-07', '2026-09-08', '2026-09-09',
               '2026-09-10', '2026-09-11', '2026-09-14', '2026-09-15',
               '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-21',
               '2026-09-22', '2026-09-23', '2026-09-24', '2026-09-25',
               '2026-09-28', '2026-09-29', '2026-09-30', '2026-10-01',
               '2026-10-02', '2026-10-05', '2026-10-06', '2026-10-07',
               '2026-10-08', '2026-10-09', '2026-10-12', '2026-10-13',
               '2026-10-14', '2026-10-15', '2026-10-16', '2026-10-19',
               '2026-10-20', '2026-10-21', '2026-10-22', '2026-10-23',
               '2026-10-26', '2026-10-27', '2026-10-28', '2026-10-29',
               '2026-10-30', '2026-11-02', '2026-11-03', '2026-11-04',
               '2026-11-05', '2026-11-06', '2026-11-09', '2026-11-10',
               '2026-11-11', '2026-11-12', '2026-11-13', '2026-11-16',
               '2026-11-17', '2026-11-18', '2026-11-19', '2026-11-20',
               '2026-11-23', '2026-11-24', '2026-11-25', '2026-11-26',
               '2026-11-27', '2026-11-30', '2026-12-01', '2026-12-02',
               '2026-12-03', '2026-12-04', '2026-12-07', '2026-12-08',
               '2026-12-09', '2026-12-10', '2026-12-11', '2026-12-14',
               '2026-12-15', '2026-12-16', '2026-12-17', '2026-12-18',
               '2026-12-21', '2026-12-22', '2026-12-23', '2026-12-24',
               '2026-12-25', '2026-12-28', '2026-12-29', '2026-12-30',
               '2026-12-31'],
              dtype='datetime64[us]', freq='B')

In [41]:
pd.date_range("2026-1-1", "2026-12-31", freq="MS")

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01',
               '2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01', '2026-11-01', '2026-12-01'],
              dtype='datetime64[us]', freq='MS')

In [43]:
pd.date_range("2026-1-1", "2026-12-31", freq="ME")

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[us]', freq='ME')

In [47]:
pd.date_range("2026-1-1", "2026-12-31", freq="WOM-2SUN")

DatetimeIndex(['2026-01-11', '2026-02-08', '2026-03-08', '2026-04-12',
               '2026-05-10', '2026-06-14', '2026-07-12', '2026-08-09',
               '2026-09-13', '2026-10-11', '2026-11-08', '2026-12-13'],
              dtype='datetime64[us]', freq='WOM-2SUN')

In [ ]:
# pd.date_range("2026-1-1", "2026-12-31", freq="QE-JAN")