## [문제1] 아래 코드를 활용해 주어진 문제에 대한 코드를 작성하시오.
-------------------------

In [1]:
%pip install pandas

Requirement already satisfied: pandas in C:\Users\곽나영\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\곽나영\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\곽나영\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\곽나영\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\곽나영\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [28]:
data = [
    ["037730", "3R", 1510, 7.36],
    ["036360", "3SOFT", 1790, 1.65],
    ["005760", "ACTS", 1185, 1.28],
]
columns = ["종목코드", "종목명", "현재가", "등락률"]
df = pd.DataFrame(data=data, columns=columns)
df.set_index('종목코드', inplace=True)
df

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
005760   ACTS  1185  1.28

### (1) 데이터프레임에서 037730 종목의 등락률을 출력하세요.

In [29]:
df.loc[["037730"], ["등락률"]]

         등락률
종목코드
037730  7.36

### (2) 데이터프레임에서 iloc 속성을 사용하여 첫번째, 두번째 행을 슬라이싱하세요.

In [30]:
df.iloc[:2]

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

### (3) 데이터프레임에서 loc 속성을 사용하여 첫번째, 두번째 행을 슬라이싱하세요.

In [31]:
df.loc[:"036360"]

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

### (4) 데이터프레임에서 iloc 속성을 사용하여 첫 번째 컬럼을 인덱싱하세요.

In [32]:
df.iloc[[0,]]

       종목명   현재가   등락률
종목코드
037730  3R  1510  7.36

### (5) 데이터프레임에서 iloc 속성을 사용하여 '037730' 종목의 '종목명', '현재가' 컬럼을 선택하세요.

In [54]:
df.iloc[0,[0,1]]

테마     2차전지(생산)
종목명     SK이노베이션
Name: 0, dtype: str

### (6) 데이터프레임에서 현재가가 1500 이상인 값만 가져와보세요.

In [34]:
reslut = df.loc[df['현재가'] >= 1500]
reslut

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

### (7) 데이터프레임에서 현재가가 1,500원 이상이면서 1,700원 미만인 값만 필터링 해보세요.

In [35]:
reslut = (df['현재가'] >= 1500)
reslut2 = (df['현재가'] < 1700)

df.loc[reslut & reslut2]

       종목명   현재가   등락률
종목코드
037730  3R  1510  7.36

-------
## [문제2] 아래 코드를 활용해서 주어진 문제에 대한 코드를 작성하시오.

In [36]:
data = [
    ["2차전지(생산)", "SK이노베이션", 10.19, 1.29],
    ["해운", "팬오션", 21.23, 0.95],
    ["시스템반도체", "티엘아이", 35.97, 1.12],
    ["해운", "HMM", 21.52, 3.20],
    ["시스템반도체", "아이에이", 37.32, 3.55],
    ["2차전지(생산)", "LG화학", 83.06, 3.75]
]

columns = ["테마", "종목명", "PER", "PBR"]
df = pd.DataFrame(data=data, columns=columns)
df

         테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
1        해운      팬오션  21.23  0.95
2    시스템반도체     티엘아이  35.97  1.12
3        해운      HMM  21.52  3.20
4    시스템반도체     아이에이  37.32  3.55
5  2차전지(생산)     LG화학  83.06  3.75

### (1) 데이터프레임에서 테마별 PER, PBR의 평균을 계산하세요.

In [37]:
df.groupby(["테마"]).mean(numeric_only=True)

             PER    PBR
테마
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.375  2.075

### (2) 데이터프레임에서 테마별 종목의 개수를 계산하세요.

In [38]:
df.groupby(["테마"]).count().iloc[:,[0]]
df.groupby(["테마"]).size()

테마
2차전지(생산)    2
시스템반도체      2
해운          2
dtype: int64

### (3) 데이터프레임에서 테마별 PER의 평균을 계산하세요.

In [39]:
df.groupby((["테마"]))[["PER"]].mean()

             PER
테마
2차전지(생산)  46.625
시스템반도체    36.645
해운        21.375

### (4) 데이터프레임에 대해 테마로 그룹화한 후 PER, PBR 컬럼을 슬라이싱하세요. 그 다음 두 컬럼에 대한 평균을 계산하세요.

In [40]:
df.groupby((["테마"]))[["PER","PBR"]].mean()

             PER    PBR
테마
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.375  2.075

In [41]:
re = df.groupby(["테마"])
re[["PER","PBR"]].mean()

             PER    PBR
테마
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.375  2.075

### (5) 데이터프레임에 대해서 '테마' 컬럼으로 그룹화한 후 PER 컬럼은 max, PBR 컬럼은 min 함수를 적용해보세요.

In [42]:
df.groupby((["테마"])).max().iloc[:,[1]]

            PER
테마
2차전지(생산)  83.06
시스템반도체    37.32
해운        21.52

In [43]:
df.groupby((["테마"])).min().iloc[:,[2]]

           PBR
테마
2차전지(생산)  1.29
시스템반도체    1.12
해운        0.95

--------------
## [문제3] 아래 코드를 활용해서 주어진 문제에 대한 코드를 작성하시오.

In [44]:
import pandas as pd

data1 = {
    'ID': [100, 101, 102, 103],
    'Name': ['Brayden', 'Clara', 'Ella', 'Oliver']
}

data2 = [
    [100, "삼성전자"],
    [100, "LG전자"],
    [101, "카카오"],
    [101, "NAVER"],
    [101, "현대차"]
]

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data=data2, columns=['ID', '종목명'])

In [45]:
df

         테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
1        해운      팬오션  21.23  0.95
2    시스템반도체     티엘아이  35.97  1.12
3        해운      HMM  21.52  3.20
4    시스템반도체     아이에이  37.32  3.55
5  2차전지(생산)     LG화학  83.06  3.75

### (1) df1과 df2를 'ID'라는 컬럼명을 기준으로 'inner' 방식으로 병합하세요.

In [46]:
df3 = pd.merge(df1, df2, how= "inner")
df3

    ID     Name    종목명
0  100  Brayden   삼성전자
1  100  Brayden   LG전자
2  101    Clara    카카오
3  101    Clara  NAVER
4  101    Clara    현대차

### (2) df1과 df2를 'ID’라는 컬럼명을 기준으로 ‘outer’ 방식으로 병합하세요.

In [47]:
df4 = pd.merge(df1, df2, how= "outer")
df4

    ID     Name    종목명
0  100  Brayden   삼성전자
1  100  Brayden   LG전자
2  101    Clara    카카오
3  101    Clara  NAVER
4  101    Clara    현대차
5  102     Ella    NaN
6  103   Oliver    NaN

### (3) 데이터프레임에서 df1의 'ID'와 df2의 '아이디' 컬럼을 기준으로 merge 하세요.(아래 코드 참조)

In [48]:
df2 = pd.DataFrame(data=data2, columns=['아이디', '종목명'])

In [49]:
df3 = pd.merge(df1, df2, left_on="ID", right_on="아이디")
df3

    ID     Name  아이디    종목명
0  100  Brayden  100   삼성전자
1  100  Brayden  100   LG전자
2  101    Clara  101    카카오
3  101    Clara  101  NAVER
4  101    Clara  101    현대차

--------------
## [문제4] 다음 데이터프레임에서 df1, df2의 인덱스를 기준으로 merge 하는 코드를 작성하시오.

In [50]:
import pandas as pd

data1 = {
    'ID': [100, 101, 102, 103],
    'Name': ['Brayden', 'Clara', 'Ella', 'Oliver']
}
data2 = [
    [100, "삼성전자"],
    [100, "LG전자"],
    [101, "카카오"],
    [101, "NAVER"],
    [101, "현대차"]
]

df1 = pd.DataFrame(data1)
df1.set_index('ID', inplace=True)
df2 = pd.DataFrame(data=data2, columns=['ID', '종목명'])
df2.set_index('ID', inplace=True)

In [51]:
df3 = pd.merge(df1, df2,how="outer" ,left_index=True, right_index=True)
df3

        Name    종목명
ID
100  Brayden   삼성전자
100  Brayden   LG전자
101    Clara    카카오
101    Clara  NAVER
101    Clara    현대차
102     Ella    NaN
103   Oliver    NaN

In [52]:
df3 = pd.merge(df1, df2,left_index=True, right_index=True)
df3

        Name    종목명
ID
100  Brayden   삼성전자
100  Brayden   LG전자
101    Clara    카카오
101    Clara  NAVER
101    Clara    현대차